// <auto-generated />
namespace Locadora.Veiculos.Dados.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class MigracaoInical : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MigracaoInical));
        
        string IMigrationMetadata.Id
        {
            get { return "202009292114263_MigracaoInical"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
